before_install:
  - sudo apt-get update
  - sudo apt-get install git gcc build-essential cmake bison flex ruby valgrind
  - gem install rspec

compiler:
  - clang
  - gcc

script: make test memtest bench

