print('Loading Redstone...')

define_behavior('push_move')
define_behavior('push_break')
define_behavior('power_wire')
define_behavior('power_conductor')
define_behavior('power_torch')
define_behavior('power_piston')
define_behavior('power_repeater')
define_behavior('power_comparator')
define_behavior('power_switch')

define_type('air',        0)
define_type('insulator',  0)
define_type('wire',       1)
define_type('conductor',  1)
define_type('torch',      2)
define_type('piston',     2)
define_type('repeater',   3)
define_type('comparator', 3)
define_type('switch',     3)

